CREATE DATABASE CadastroClienteDB;
GO
 
USE CadastroClienteDB;
GO
 
CREATE TABLE CLIENTES
(
    ClienteID INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    CPF NVARCHAR(20)NOT NULL,
    DataNasct DATE,
    DataRegistro DATE
);
GO

CREATE TABLE CONTATOS
(
    ContatoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Telefone NVARCHAR(20),
    Email NVARCHAR(100)
);
GO

CREATE TABLE ENDERECO
(
    EnderecoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Logradouro NVARCHAR(100),
    Numero INT, 
    Bairro NVARCHAR(50),
    Cidade NVARCHAR(50),
    Estado NVARCHAR(50),
    Cep NVARCHAR(20)
);
GO

CREATE TABLE OBSERVACOES
(
    ObservacaoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Situacao NVARCHAR (20),
    Observacao NVARCHAR (200)
);
GO

ALTER TABLE CONTATOS
ADD CONSTRAINT FK_CONTATO_CLIENTE
FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID);
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE
FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID);
GO

ALTER TABLE OBSERVACOES
ADD CONSTRAINT FK_OBSERVACOES_CLIENTE
FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID);
GO

CREATE TABLE PRODUTOS
(
    ProdutoID INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Descricao NVARCHAR(500) NOT NULL,
    Preco DECIMAL(10,2) NOT NULL,
    Estoque INT NOT NULL,
    Categoria NVARCHAR(50) NOT NULL,
    Imagem VARBINARY(MAX) NULL,
    DataRegistro DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE VENDAS
(
    VendaID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    DataVenda DATETIME NOT NULL,
    ValorTotal DECIMAL(10,2) NOT NULL,
    Desconto DECIMAL(10,2) NULL,
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID)
);
GO

CREATE TABLE VENDAS_ITENS
(
    ItemVendaID INT IDENTITY(1,1) PRIMARY KEY,
    VendaID INT NOT NULL,
    ProdutoID INT NOT NULL,
    Quantidade INT NOT NULL,
    PrecoUnitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ITENS_VENDA FOREIGN KEY (VendaID) REFERENCES VENDAS(VendaID),
    CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ProdutoID) REFERENCES PRODUTOS(ProdutoID)
);
GO

SELECT*FROM VENDAS_ITENS
GO

SELECT*FROM VENDAS
GO

/*
TABELAS E TRIGGER PARA TABELAS DE AUDITORIA.
AJUDA DE IA (GEMINI) PARA ELABORAÇÃO E APRENDIZADO DE SINTAXES E FUNCIONALIDADES
*/

CREATE TABLE AUDITORIA
(
    AuditoriaID INT IDENTITY(1,1) PRIMARY KEY,
    TabelaAfetada NVARCHAR(50),
    TipoOperacao NVARCHAR(20),
    DescricaoRegistro NVARCHAR(MAX),
    DataEvento DATETIME DEFAULT GETDATE()
);
GO

CREATE TRIGGER trg_Aud_Clientes ON CLIENTES AFTER DELETE, UPDATE AS
BEGIN
    IF NOT EXISTS (SELECT * FROM inserted)
        INSERT INTO AUDITORIA (TabelaAfetada, TipoOperacao, DescricaoRegistro)
        SELECT 'CLIENTES', 'EXCLUÍDO', 'Cliente: ' + Nome + ' (CPF: ' + CPF + ')' FROM deleted;
    ELSE
        INSERT INTO AUDITORIA (TabelaAfetada, TipoOperacao, DescricaoRegistro)
        SELECT 'CLIENTES', 'ALTERADO', 'ID: ' + CAST(i.ClienteID AS VARCHAR) + ' - Nome: ' + i.Nome FROM deleted d INNER JOIN inserted i ON d.ClienteID = i.ClienteID;
END;
GO

CREATE TRIGGER trg_Aud_Produtos ON PRODUTOS AFTER DELETE, UPDATE AS
BEGIN
    IF NOT EXISTS (SELECT * FROM inserted)
        INSERT INTO AUDITORIA (TabelaAfetada, TipoOperacao, DescricaoRegistro)
        SELECT 'PRODUTOS', 'EXCLUÍDO', 'Prod: ' + Nome FROM deleted;
    ELSE
        INSERT INTO AUDITORIA (TabelaAfetada, TipoOperacao, DescricaoRegistro)
        SELECT 'PRODUTOS', 'ALTERADO', 'Prod: ' + i.Nome + ' | Preço: ' + CAST(i.Preco AS VARCHAR) FROM deleted d INNER JOIN inserted i ON d.ProdutoID = i.ProdutoID;
END;
GO

CREATE TRIGGER trg_Aud_Vendas ON VENDAS AFTER DELETE AS
BEGIN
    INSERT INTO AUDITORIA (TabelaAfetada, TipoOperacao, DescricaoRegistro)
    SELECT 'VENDAS', 'EXCLUÍDO', 'Venda ID: ' + CAST(VendaID AS VARCHAR) + ' | Total: ' + CAST(ValorTotal AS VARCHAR) FROM deleted;
END;
GO