CREATE DATABASE KERN
GO

USE KERN
GO

/*CADASTRO FUNCIONARIOS*/
CREATE TABLE Funcionarios (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NomeFunc VARCHAR(100),
    Usuario VARCHAR(50) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    Senha VARCHAR(MAX),
    FotoFunc VARBINARY(MAX)    
);
GO

/*CADASTRO CLIENTE*/
CREATE TABLE CLIENTES (
    ClienteID INT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    CPF NVARCHAR(14) NOT NULL UNIQUE,
    DataNasct DATE,
    DataRegistro DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE CONTATOS (
    ContatoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Telefone NVARCHAR(20),
    Email NVARCHAR(100),
    CONSTRAINT FK_CONTATO_CLIENTE FOREIGN KEY (ClienteID) 
        REFERENCES CLIENTES(ClienteID) ON DELETE CASCADE
);
GO

CREATE TABLE ENDERECO (
    EnderecoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Logradouro NVARCHAR(100),
    Numero NVARCHAR(10),
    Bairro NVARCHAR(50),
    Cidade NVARCHAR(50),
    Estado CHAR(2),
    Cep NVARCHAR(10),
    CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (ClienteID) 
        REFERENCES CLIENTES(ClienteID) ON DELETE CASCADE
);
GO

CREATE TABLE OBSERVACOES (
    ObservacaoID INT IDENTITY(1,1) PRIMARY KEY,
    ClienteID INT NOT NULL,
    Situacao NVARCHAR(20),
    Observacao NVARCHAR(MAX),
    CONSTRAINT FK_OBSERVACOES_CLIENTE FOREIGN KEY (ClienteID) 
        REFERENCES CLIENTES(ClienteID) ON DELETE CASCADE
);
GO

CREATE INDEX IX_CLIENTES_NOME ON CLIENTES(Nome);
GO

/*CADASTRO PRODUTO*/
CREATE TABLE PRODUTOS
(
    ProdutoID INT IDENTITY(1,1) PRIMARY KEY,
    CodigoBarras NVARCHAR(50) NULL,
    Nome NVARCHAR(100) NOT NULL,
    Descricao NVARCHAR(500) NOT NULL,
    Preco DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    Estoque INT NOT NULL DEFAULT 0,
    Categoria NVARCHAR(50) NOT NULL,
    Imagem VARBINARY(MAX) NULL,
    DataRegistro DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE INDEX IX_PRODUTOS_CodigoBarras ON PRODUTOS(CodigoBarras);
GO

CREATE INDEX IX_PRODUTOS_Nome ON PRODUTOS(Nome);
GO

/*CADASTRO VENDAS*/
CREATE TABLE VENDAS (
    VendaID INT PRIMARY KEY IDENTITY(1,1),
    ClienteID INT NOT NULL,
    FuncionarioID INT NOT NULL,
    DataVenda DATETIME DEFAULT GETDATE(),
    ValorTotal DECIMAL(10,2) NOT NULL,
    Desconto DECIMAL(10,2) DEFAULT 0,
    TipoEntrega VARCHAR(20), -- 'RETIRADA' ou 'ENTREGA'
    EnderecoEntrega NVARCHAR(MAX),
    FormaPagamento VARCHAR(50),
    BandeiraCartao VARCHAR(30),
    Parcelas INT,
    ValorParcelado_Texto NVARCHAR(50),
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID),
    CONSTRAINT FK_VENDAS_FUNCIONARIO FOREIGN KEY (FuncionarioID) REFERENCES Funcionarios(ID)
);

CREATE TABLE VENDAS_ITENS (
    ItemVendaID INT PRIMARY KEY IDENTITY(1,1),
    VendaID INT NOT NULL,
    ProdutoID INT NOT NULL,
    Quantidade INT NOT NULL,
    PrecoUnitario DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ITENS_VENDA FOREIGN KEY (VendaID) REFERENCES VENDAS(VendaID),
    CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ProdutoID) REFERENCES PRODUTOS(ProdutoID)
);
GO
